// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbcgihfthsjpwbygmrtg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpiY2dpaGZ0aHNqcHdieWdtcnRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNjkzMjMsImV4cCI6MjA3MDc0NTMyM30.3J60uvqGgh1hr3iwDGcNZubKWm5sxhvC4vEg5EYdTJg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});